apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: astra-applications-manager
  namespace: argocd
spec:
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/
  goTemplate: true # enable to use golang syntax in the application set
  goTemplateOptions: ["missingkey=error"] # error if the key is missing
  generators:
    - matrix:
        generators:
          - git:
              repoURL: http://git.example.com/jerry/gitops.git
              revision: main
              requeueAfterSeconds: 60 # requeue after 60 seconds
              files:
                - path: astra/**/config.json
          - list:
              elementsYaml: |
                {{- $envs := list -}}
                {{- range $env, $config := .environments -}}
                {{- $envs = append $envs (dict "env" $env) -}}
                {{- end -}}
                {{ $envs | toJson }}
  template:
    metadata:
      name: '{{.path.basename}}-{{.env}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: '{{.project}}'
      destination:
        name: '{{index .environments .env "clusterName"}}'
        namespace: '{{.namespace}}'
      sources:
        - repoURL: '{{.source.repoURL}}'
          targetRevision: '{{.source.targetRevision}}'
          path: '{{.source.path}}'
          helm:
            valueFiles:
              - values.yaml
              - '{{index .environments .env "valuesFile"}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
